### PR TITLE
Use Apache 2.0 as the license

### PR DESCRIPTION
**Pull request by MaxDesiatov**
I assume this makes sense as the same license that Apple's Swift toolchain uses.

### CODE REVIEW

**Comment by compnerd** [comment]
I really think that this is inappropriate.  The work that you so casually relicense here is not your doing, nor have you done any prior work towards.  I see no clear argument to even request that the work be relicensed.  Even if I were to agree to relicense the code, which is a separate conversation, this is not the way to do that - the author controls the license under which the work is released, someone else should not be making such a change.

**Comment by MaxDesiatov** [comment]
I apologize, I did not mean to relicense any work whatsoever, I'm sorry that it appeared this way. I only wanted to propose a license that could be appropriate for such project and start a discussion based on that.

I wanted to contribute, but didn't see find any license file, so it was unclear to me if contributions would be accepted at all. Would it be better if I create a separate issue about the absence of a LICENSE file?

**Comment by MaxDesiatov** [comment]
To clarify, I wasn't sure what the current license is, so my understanding was that the project was unlicensed. GitHub provides a way to propose a license [in project insights], which I used to propose one, I did not intend to relicense the project in any way, only to propose some license before making any contributions.

Again, apologies for the confusion, I didn't mean to propose this casually, and I'm sorry it turned out this way.

**Comment by compnerd** [comment]
Ah, I see.  Thanks for pointing out the missing file - I've added that now.  The sources had the SPDX identifier, but I agree with your point that a clear LICENSE file is far more explicit.  The work was not meant to be unlicensed, that would be a serious problem for anyone wishing to use the work for any reason.  The only problem was that I had only done that on the files (and when I looked at the files when I wrote up some documentation, I realized that I was missing the copyright and license identifier).

I look forward to the contributions :)

**Pull request closed without merging**
